

type Activity {
  id: ID!
  title: String!
  description: String
  timeStamp: Long!
  user: User!
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  fullName: String!
  position: String!
  access_level: String!
  email: String!
  recent_activities: [Activity]! 
  uid: String!
  added_by: User
}

type File {
  id: ID!
  url: String!
  path: String!
  vehicle: Vehicle!
}

type Feature {
  id: ID!
  header: String!
  features: [String]!
  vehicle: Vehicle!
}


type Address {
  address_line_1: String!
  address_line_2: String!
  address_line_3: String
  parish: String!
  country: String!
  state: String!
}


type Client {
  firstName: String!
  lastName: String!
  fullName:  String!
  email: String!
  mobile:  String
  address: Address
}

type Request {
  id: ID!
  vehicle: Vehicle!
  client: Client!
  type: String!
  details: String
  state: Boolean!
  timeStamp: Long!
}


type Vehicle {
  id: ID!
  year: Int!
  make: String!
  model: String!
  submodel: String
  body: String!
  trans: String!
  color: String!
  engine_no: String!
  chassis: String!
  mileage: String!,
  engine_size: String!
  location: String!
  history: String!
  arrival: Long
  price: String!
  price_cond: String!
  price_visible: Boolean!
  timeStamp: Long!
  last_update: Long!
  isFeatured: Boolean!
  isVisible: Boolean!

  added_by: User
  updated_by: User

  isAvailable: Boolean!

  request: [Request]!
  saves: Int!

  title: String!
  media: [File]

  features: [Feature]!
  invoice: Invoice
}

type Account {
  id: ID!
  type: String!
  title: String!
  details: String
  invoice: Invoice!
}

type Invoice {
  id: ID!
  client: Client!
  invoice_no: Int!
  vehicle: Vehicle!
  accounts: [Account]!
  timeStamp: Long!
  user: User!
}

type Query {
  Inventory: [Vehicle]
  allUsers: [User]
  allRequests: [Request]
  allInvoices: [Invoice]
}
