import Head from 'next/head'
import { Box, Grid, GridItem, Text } from '@chakra-ui/react'
import FeatherIcon from 'feather-icons-react'

const GridResponsiveness = {
    minH: '100vh',
    templateColumns: 'repeat(12,1fr)',
    templateRows: 'repeat(8,1fr)',
    justifyContent: 'center',
    alignItems: 'center'
}


const GridItemResponsiveness = {
    rowStart: { base: 1, md: 2 },
    rowEnd: { base: 9, md: 8 },
    colStart: { base: 1, md: 3, lg: 4 },
    colEnd: { base: 13, md: 11, lg: 10 }
}


export default function Home() {
    return (

        <>
            <Head>
                <title>Autozone System Control | Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box bgImage={`url('/images/authbg.jpg')`} backgroundSize={'cover'}>
                <Grid {...GridResponsiveness} >
                    <GridItem {...GridItemResponsiveness} >
                        <Box p={10} bgColor={'white'}>

                            <Text>Login</Text>


                            <form>
                            </form>

                        </Box>
                    </GridItem>

                </Grid>
            </Box>
        </>
    )
}