import Head from 'next/head'
import { Box } from '@chakra-ui/react'

export default function Home() {
  return (

    <>
      <Head>
        <title>Autozone System Control</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box> </Box>
    </>
  )
}
