import React from 'react'
import Head from 'next/head'

import { Box, HStack, IconButton, useDisclosure, Text, Menu, MenuButton, MenuList, MenuItem, Tooltip, Divider } from '@chakra-ui/react'
import FeatherIcon from 'feather-icons-react'
import DrawerContainer from './DrawerContainer'
import NavMenu from './NavMenu'
import { useRouter } from 'next/router'


function ProfileMenu() {
    return (
        <Menu>
            {({ isOpen }) => (
                <>
                    <MenuButton variant={'ghost'}>
                        <HStack alignItems={'center'} >
                            <FeatherIcon icon={'user'} />
                            <Text mx={2} fontWeight={'medium'} >{isOpen ? 'Hello, Joel' : 'Joel Henry'}</Text>
                        </HStack>
                    </MenuButton>
                    <MenuList>
                        <MenuItem>
                            <HStack fontSize={'sm'} spacing={2} width={'full'} alignItems={'center'}>
                                <FeatherIcon size={16} icon={'user'} />
                                <Text>Profile</Text>
                            </HStack>
                        </MenuItem>
                        <MenuItem>
                            <HStack fontSize={'sm'} spacing={2} width={'full'} alignItems={'center'}>
                                <FeatherIcon size={16} icon={'log-out'} />
                                <Text>Sign Out</Text>
                            </HStack>
                        </MenuItem>
                    </MenuList>
                </>
            )}
        </Menu>
    )
}


export default function Dashboard({ children, page }) {

    const { isOpen, onOpen, onClose } = useDisclosure()
    const drawerControl = React.useRef()
    const [loaded, setLoaded] = React.useState(false)

    const { back } = useRouter()


    React.useEffect(() => setLoaded(true), [])


    return (
        <>
            <Head>
                <title>Autozone System Control | {page}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box position={'relative'} minH={'100vh'} bgColor={'whitesmoke'} paddingLeft={0}>
                <DrawerContainer onClose={onClose} isOpen={isOpen} toggleRef={drawerControl}>
                    <NavMenu page={page} />
                </DrawerContainer>

                <HStack zIndex={'modal'} justifyContent={'end'} p={5} bgColor={'white'} top={0} left={0} right={0} position={'sticky'}>
                    <IconButton
                        display={{ base: 'flex', lg: 'none' }}
                        onClick={onOpen}
                        ref={drawerControl}
                        borderRadius={'full'}
                        ml={5}
                        variant={'ghost'}
                        icon={<FeatherIcon icon={'menu'} />}
                    />

                    <Box display={{ base: 'none', lg: 'unset' }}>
                        {loaded ? <ProfileMenu /> : <></>}
                    </Box>

                </HStack>



                <Box
                    zIndex={'modal'}
                    display={{ base: 'none', lg: 'unset' }}
                    bgColor={'white'}
                    position={'fixed'}
                    top={0}
                    bottom={0}
                    left={0}
                    pl={5}
                    pr={40}
                    py={10}
                    mr={5}  >


                    <NavMenu page={page} />
                </Box>

                <Box ml={{ base: 'unset', lg: 80 }} mt={10} pb={10} pr={{base: 1, lg: 5 }} pl={{ base: 1, lg: 50 }}>
                    <HStack spacing={30} px={5}>
                        {
                            page === 'Dashboard'
                                ? <></>
                                : <Tooltip label={'Go Back'}>
                                    <IconButton onClick={back} colorScheme={'red'} variant={'ghost'} borderRadius={'full'} size={'xl'} icon={<FeatherIcon icon={'chevron-left'} />} />
                                </Tooltip>
                        }


                        <Text mx={10} color={'red.600'} fontWeight={'medium'} fontSize={'2xl'}>{page}</Text>
                    </HStack>
                    <Divider my={2} />


                    {children}
                </Box>
            </Box>
        </>

    )
}